<h3>NumPy<h3>

In [ ]:
import numpy as np

Dizi oluşturalım 2 tane

In [ ]:
x = np.array([ 5, 8, 17])
print(x)

In [ ]:
y = np.array([[2,13,30],[6,11,22]])
print(y)

dizi boyutu ögrenme(ndim)

In [ ]:
x.ndim

In [ ]:
y.ndim

Satır sütun sayılarını öğrenme(shape)

In [ ]:
y.shape

In [ ]:
x.shape

Dizinin istenilen hücresine erişme [2.satır,3.sütun] (0'dan başlayacağı için 1 eksiğini yazıyoruz)

In [ ]:
y[1,2]

Direkt satır ulaşmak için

In [ ]:
y[1]

1. satırdaki 2. sutun ve 1. satır 3.sütun ulaşmak için

In [ ]:
y[0,1:]

Hücrenin içindeki sayıyı değiştirme

In [ ]:
y[0,1]=20
y[0,1]

<h4>Otomatik dizi oluşturma<h4>

Hepsi sıfır olan 3x4 matris 

In [34]:
matrisZ=np.zeros((3,4))
matrisZ

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Hepsi aynı olan 2x4 lük matris

In [35]:
matrisO=np.full((2,4),8)
matrisO

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

Ramdom matris oluşturma float

In [36]:
matrisRnd=np.random.rand(1,3)
matrisRnd

array([[0.573993  , 0.69276874, 0.99680492]])

random 0 50 arası integer matris oluşturma

In [38]:
matrisRndint=np.random.randint(0,50,size=(2,3))
matrisRndint

array([[ 7, 39, 11],
       [37, 45,  4]])

Dizi kopyalama

In [39]:
a=np.array([3,5,8])
b=a.copy()
b[1]=12
print(a)

[3 5 8]


In [40]:
print(b)

[ 3 12  8]


Matrisde Matematik işlemleri

In [43]:
a=np.array([2,5,7,9])
a+1

array([ 3,  6,  8, 10])

In [44]:
a*2

array([ 4, 10, 14, 18])

In [45]:
a/2

array([1. , 2.5, 3.5, 4.5])

In [47]:
a**2

array([ 4, 25, 49, 81], dtype=int32)

In [48]:
b=np.array([4,11,14,17])
a+b

array([ 6, 16, 21, 26])

<h4>İstatistik<h4>