<h3>NumPy<h3>

In [112]:
import numpy as np

Dizi oluşturalım 2 tane

In [113]:
x = np.array([ 5, 8, 17])
print(x)

[ 5  8 17]


In [114]:
y = np.array([[2,13,30],[6,11,22]])
print(y)

[[ 2 13 30]
 [ 6 11 22]]


dizi boyutu ögrenme(ndim)

In [115]:
x.ndim

1

In [116]:
y.ndim

2

Satır sütun sayılarını öğrenme(shape)

In [117]:
y.shape

(2, 3)

In [118]:
x.shape

(3,)

Dizinin istenilen hücresine erişme [2.satır,3.sütun] (0'dan başlayacağı için 1 eksiğini yazıyoruz)

In [119]:
y[1,2]

22

Direkt satır ulaşmak için

In [120]:
y[1]

array([ 6, 11, 22])

1. satırdaki 2. sutun ve 1. satır 3.sütun ulaşmak için

In [121]:
y[0,1:]

array([13, 30])

Hücrenin içindeki sayıyı değiştirme

In [122]:
y[0,1]=20
y[0,1]

20

<h4>Otomatik dizi oluşturma<h4>

Hepsi sıfır olan 3x4 matris 

In [123]:
matrisZ=np.zeros((3,4))
matrisZ

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Hepsi aynı olan 2x4 lük matris

In [124]:
matrisO=np.full((2,4),8)
matrisO

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

Ramdom matris oluşturma float

In [125]:
matrisRnd=np.random.rand(1,3)
matrisRnd

array([[0.55595885, 0.56070989, 0.22850884]])

random 0 50 arası integer matris oluşturma

In [126]:
matrisRndint=np.random.randint(0,50,size=(2,3))
matrisRndint

array([[12, 15, 46],
       [18, 31, 18]])

Dizi kopyalama

In [127]:
a=np.array([3,5,8])
b=a.copy()
b[1]=12
print(a)

[3 5 8]


In [128]:
print(b)

[ 3 12  8]


Matrisde Matematik işlemleri

In [129]:
a=np.array([2,5,7,9])
a+1

array([ 3,  6,  8, 10])

In [130]:
a*2

array([ 4, 10, 14, 18])

In [131]:
a/2

array([1. , 2.5, 3.5, 4.5])

In [132]:
a**2

array([ 4, 25, 49, 81], dtype=int32)

In [133]:
b=np.array([4,11,14,17])
a+b

array([ 6, 16, 21, 26])

<h4>İstatistik<h4>

In [134]:
dizis=np.array([[1,2,3],[4,5,6]])
dizis

array([[1, 2, 3],
       [4, 5, 6]])

Matrisdeki minimum maximum sayıyı bulma ve sayıların toplamı

In [135]:
np.min(dizis)

1

In [136]:
np.max(dizis)

6

In [137]:
np.sum(dizis)

21

Dosyadan yükleme .txt uzantılı

In [138]:
filedata=np.genfromtxt('Matris.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[ 3  5  6]
 [ 5  7 11]]


In [139]:
filedata[0,0]

3